"""Regenerate SDN/TCD/YEM fixture JSONs from the current pipeline state.

Usage:
    .venv/bin/python -m tests.regenerate_fixtures

Fixtures are hand-verified against source Parquet once committed — see
spec-data-pipeline.md §13 (DoD).
"""
from __future__ import annotations

import json
from pathlib import Path

import polars as pl

from pipeline.transform.country_year import build_country_year_table

FIXTURE_DIR = Path(__file__).parent / "fixtures"
ANALYSIS_YEAR = 2025


def _row_payload(table: pl.DataFrame, iso3: str) -> dict | None:
    sub = table.filter(pl.col("iso3") == iso3)
    if sub.is_empty():
        return None
    row = sub.row(0, named=True)
    row["qa_flags"] = list(row["qa_flags"])
    # Floats with NaN would break JSON; convert safely.
    for k, v in list(row.items()):
        if isinstance(v, float) and (v != v):
            row[k] = None
    return row


def main() -> None:
    FIXTURE_DIR.mkdir(exist_ok=True)
    table = build_country_year_table(ANALYSIS_YEAR, 1_000_000, True)
    for iso3 in ("SDN", "TCD", "YEM"):
        payload = _row_payload(table, iso3)
        fixture = {
            "iso3": iso3,
            "analysis_year": ANALYSIS_YEAR,
            "expected_in_cohort": payload is not None,
            "expected_country_row": payload,
            "note": (
                "Regenerated by tests/regenerate_fixtures.py. Hand-verify pin, "
                "requirements_usd, funding_usd, coverage_ratio, chronic_years "
                "against source Parquet before signing off."
            ),
        }
        path = FIXTURE_DIR / f"{iso3.lower()}.json"
        with path.open("w") as fh:
            json.dump(fixture, fh, indent=2, default=str)
        print(f"wrote {path}")


if __name__ == "__main__":
    main()
